spring:
  cache:
    type: hazelcast
  application:
    name: hazelcast-cache

hazelcast:
  cluster-name: hazelcast-cluster
  instance-name: hazelcast-instance
  network:
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - 127.0.0.1:5701
          - 127.0.0.1:5702

server:
  port: 8081
